version: '3.1'

services:

  db:
    image: mariadb
    restart: always

    environment: 
      MYSQL_ROOT_PASSWORD: very-secret-password
      MYSQL_DATABASE: backenddb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secret-password

    ports:
      - 3306:3306
    volumes:     
        - ./init:/docker-entrypoint-initdb.d
        - data:/var/lib/mysql
  
volumes:
  data: 